## These functions allow to improve efficiency of matrix inverse calculations
## by caching the inverse of a matrix rather than computing it repeatedly. 


## makeCacheMatrix function takes a matrix as an argument and returns a list that
## contains functions to set and get value of the matrix and its inverse.

makeCacheMatrix <- function(x = matrix()) {
    cacheInvMatrix <- NULL    
    set <- function(y) {
        x <<- y
        cacheInvMatrix <<- NULL
    }
    get <- function() x
    setInverse <- function(inverse) cacheInvMatrix <<- inverse
    getInverse <- function() cacheInvMatrix
    list(set = set, 
         get = get,
         setInverse = setInverse,
         getInverse = getInverse)
}

## cacheSolve function takes list generated by MakeCacheMatrix(x) as an argument
## and returns the inverse of x. It skips computing if the inverse is already
## stored in cache, or uses solve(x) and caches the inverse using setInverse 
## "method" from MakeCacheMatrix function

cacheSolve <- function(x, ...) {
    invMatrix <- x$getInverse()
    if(!is.null(invMatrix)) {   ## check whether inverse has already been calculated
        message("getting cached data")
        return(invMatrix)
    }
    data <- x$get()
    invMatrix <- solve(data, ...)
    x$setInverse(invMatrix)
    invMatrix   ## return inverse of matrix
}
